import json, base64, urllib.parse, sys
def raw(html): return '[vc_raw_html]'+base64.b64encode(urllib.parse.quote(html, safe="!'()*-._~").encode()).decode()+'[/vc_raw_html]'

faq=[
("When should I order a steel building for spring?","Plan to order by about early February for a mid-April delivery, or early January for mid-March. Delivery is typically 8 to 10 weeks from order, and the order-by dates here use the 10-week end of that range to be safe. Your written quote confirms the schedule. Start engineering, permits, and foundation planning before you order."),
("How long does it take to get a steel building?","Delivery is typically 8 to 10 weeks from order. Before ordering, allow time for engineered drawings and your permit, which varies by county or city. After delivery, erection time depends on the size of the building and your crew. Ask for a timeline for your project when you request a quote."),
("Can I pour the foundation before the building arrives?","Yes. Most buyers pour and cure the foundation while the building is being manufactured, so erection can start soon after delivery. Your engineered drawings supply the anchor bolt layout, so finish those before the pour. Confirm details with your engineer and foundation contractor."),
("Do I need a permit before ordering a steel building?","It depends on your county or city. Many buyers apply for a permit before ordering because engineered drawings are usually required. Your building is engineered for local codes, with plans prepared for permitting. Check with your local building department for exactly what they require."),
("What if I order in March?","A March 23 order would typically arrive around June 1, using a 10-week lead time. You can still build this season. Lead times can change, so confirm the current schedule in your written quote before you plan around a date."),
]
ld={"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faq]}
rows=[("March 15","January 4"),("April 1","January 21"),("April 15","February 4"),("May 1","February 20"),("May 15","March 6"),("June 1","March 23")]
table='<table class="bsb-orderby"><thead><tr><th>Building needed on site by</th><th>Order by</th></tr></thead><tbody>'+''.join(f'<tr><td>{a}</td><td>{b}</td></tr>' for a,b in rows)+'</tbody></table>'
style='<style>.bsb-orderby{width:100%;border-collapse:collapse;margin:16px 0}.bsb-orderby th{background:#1a3153;color:#fff;text-align:left;padding:10px 14px}.bsb-orderby td{padding:10px 14px;border-bottom:1px solid #dfe6f1}.bsb-orderby tbody tr:nth-child(even){background:#f3f6fa}.bsb-steps{counter-reset:s;list-style:none;padding:0;margin:16px 0}.bsb-steps li{counter-increment:s;position:relative;padding:12px 14px 12px 54px;margin-bottom:8px;background:#f3f6fa;border-radius:6px}.bsb-steps li:before{content:counter(s);position:absolute;left:12px;top:10px;width:30px;height:30px;line-height:30px;text-align:center;border-radius:50%;background:#f68a31;color:#fff;font-weight:700}.bsb-check{list-style:none;padding:0;margin:12px 0}.bsb-check li{padding:6px 0 6px 30px;position:relative}.bsb-check li:before{content:"\\2713";position:absolute;left:0;color:#f68a31;font-weight:700}.bsb-note{font-size:14px;color:#444b55}</style>'
def ct(h): return f'[vc_column_text]{h}[/vc_column_text]'
body=''
body+=ct('<p><strong>To have a steel building on site by mid-April, plan to order by about early February.</strong> Delivery is typically 8 to 10 weeks from order, so mid-March delivery means ordering by about early January. Start engineering, permits, and foundation planning before you order, because they decide whether your site is ready when the steel arrives in Utah, Idaho, or Wyoming.</p>')
body+=ct('<h2>Order-by dates for spring 2027</h2>'+table+'<p class="bsb-note">Dates assume a 10-week lead time, the long end of our 8 to 10 week range. These are estimates only. Delivery schedules are confirmed in your written quote, so ask for the current lead time before you plan around it.</p>')
body+=ct('<h2>What is the timeline from quote to finished building?</h2><p>The steps run in order, but several overlap. The manufacturing clock is only one of them.</p><ol class="bsb-steps"><li><strong>Quote and design.</strong> Confirm size, height, doors, and use.</li><li><strong>Engineered drawings.</strong> Drawings for your site\u2019s snow, wind, and seismic loads.</li><li><strong>Permit.</strong> Submit to your county or city. Review time varies widely by jurisdiction.</li><li><strong>Order.</strong> The 8 to 10 week lead time starts here.</li><li><strong>Foundation.</strong> Poured and cured while your building is manufactured. This is the step most affected by frost.</li><li><strong>Delivery.</strong> Typically 8 to 10 weeks after order.</li><li><strong>Erection.</strong> Time depends on the size of the building and your crew.</li></ol>')
body+=ct('<h2>Why does frost and thaw timing matter in Utah, Idaho, and Wyoming?</h2><p>A foundation cannot be poured into frozen or saturated ground, and a building should not arrive before the slab or piers are ready. Valley sites often thaw earlier than mountain and high-plains sites. Work backward from your expected thaw date, then add the lead time.</p>')
body+=ct('<h2>Can you pour the foundation before the building arrives?</h2><p>Yes, and most buyers should. Pour and cure the foundation while the building is being made, so erection can start soon after it is delivered. Anchor bolt layouts come from your engineered drawings, so complete those first.</p>')
body+=ct('<h2>What if you miss the spring window?</h2><p>You still have options. Tell us your target date and we will confirm the schedule choices for your project. If you are planning ahead, a foundation poured in the fall before the ground freezes may be ready for a spring delivery.</p>')
body+=ct('<h2>Checklist before you order</h2><ul class="bsb-check"><li>Land secured and zoning confirmed for your building use</li><li>Final size, eave height, doors, and insulation chosen</li><li>Permit application ready or submitted</li><li>Foundation contractor scheduled</li><li>Utilities and site access planned for delivery trucks</li></ul>')
body+='[vc_empty_space height="20px"][vc_column_text]<h2 style="text-align:center">Tell us when you need your building on site</h2><p style="text-align:center">We will help estimate your order-by date.</p>[/vc_column_text][dt_default_button link="url:%2Fquote%2F%3Futm_source%3Dblog%26utm_medium%3Dpost%26utm_campaign%3Dspring-delivery" button_alignment="btn_center" el_class="btn-orange"]Get My Order-By Date and Quote[/dt_default_button][vc_empty_space height="30px"]'
body+='[vc_column_text]<h2>Steel building ordering questions</h2>[/vc_column_text]'
body+=''.join(f'[vc_toggle title="{q}"]{a}[/vc_toggle]' for q,a in faq)
body+=ct('<p class="bsb-note"><small>General information only; not engineering, legal, tax, insurance, or financing advice. Requirements, prices, and lead times vary by site and change over time. Confirm details with your local building department, engineer, or advisor, and see your written quote or contract for what applies to your project.</small></p>')
out='[vc_row]'+'[vc_column]'+raw(style)+body+raw('<script type="application/ld+json">'+json.dumps(ld,ensure_ascii=False)+'</script>')+'[/vc_column][/vc_row]'
open(sys.argv[1],'w').write(out)
print(len(out))
